server.port: 8081


spring.datasource.username: cartuser
spring.datasource.password: cartpass
spring.datasource.url: jdbc:postgresql://host.docker.internal:5434/cart
spring.datasource.driver-class-name: org.postgresql.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.show-sql: true
spring.jpa.database: postgresql
spring.jpa.defer-datasource-initialization: true
spring.sql.init.mode: always


URL_PRODUCT: http://localhost:8083

#debug: true